### PR TITLE
enable dropdown selection and changes trigger

### PR DESCRIPTION
**Pull request by crackjack**
use browser's capabilities to trigger changes

### CODE REVIEW

**Comment by emilyzzz** [comment]
I have a double ChainedForeignKey fields, and on update on Django admin, the grand child model doesn't render value (looks like unselected).  Manually updated code according to this PR fixed the issue.  Hope this PR can be merged soon.

**Comment by roszczypalam** [comment]
@blag Is there any chance to merge it ? It solves problem with chained dropdowns in Admin edit views.

**Comment by skarzi** [comment]
is there any chance to merge this PR and release new version?

**Comment by manelclos** [comment]
This PR is against `js-unlinting-fixes` branch which hasn't been updated in two years, and probably not merged because of problems on that branch. Releases are based off master. Could you try current master and see if the fix still applies?

**Comment by manelclos** [comment]
As I suspected, applying this change on master breaks the location example in the test_app: the third select is no longer updated and you are left in an inconsistent state.

Please take into account that when updating a form control using javascript no `change` signal is generated, and current version of django-smart-selects seems to rely on manually emitting the signal.

Hope this helps.

**Comment by manelclos** [comment]
If anyone using the old `js-unlinting-fixes` tries to update to current `master` has any problems, I would be happy to help. We can document the process if any special change is needed.

**Comment by manelclos** [comment]
closing due to inactivity, please reopen if necessary.

**Pull request closed without merging**
