### PR TITLE
Improve django support

### PR DESCRIPTION
**Pull request by manelclos**
Support django 1.8-3.0. Update travis matrix.

Depends on https://github.com/jazzband/django-smart-selects/pull/289
Depends on https://github.com/jazzband/django-smart-selects/pull/288

### CODE REVIEW

**Comment by blag** [comment]
Looks good to me. Thanks for tweaking the docs and adding tests!

However, I'm no longer the maintainer of this project, and I don't really have enough free time nowadays to review code for this project. Moving forward, please stop at-mentioning me in comments and requesting reviews from me.

**Comment by raybesiga** [comment]
@manelclos @jezdez any idea when this will be merged?

**Comment by manelclos** [comment]
@raybesiga done

**Comment by raybesiga** [comment]
Thank you @manelclos!

**Comment by Ermak84** [comment]
Good day.
python 3.9
ModuleNotFoundError: No module named 'smart_selects'

**Pull request merged**
