### PR TITLE
bump version to 1.6.0

### PR DESCRIPTION
**Pull request by manelclos**

### CODE REVIEW

**Comment by jezdez** [comment]
@manelclos Hey there, that's great, I have a few more updates in #323 that would be great to have in a release. I wouldn't mind if you would do a last 1.5.x release for Python 2 support, and then do a 1.6.x release for the things in #323.

Please let me know if you need any help with this, I understand the migration to GitHub Actions is a bit more involved, but given Travis' changes with regard to OSS projects something we need to tackle. Thanks for your help!

**Comment by manelclos** [comment]
Hi @jezdez, I wanted to have a release before merging the PR that removes support for Django < 2.2.

But I found the move to tox makes travis fail on django-master. Before it was ignored, so I tried this: https://github.com/jazzband/django-smart-selects/compare/fix-travis?expand=1

Are we moving away from Travis?

**Comment by manelclos** [comment]
@jezdez ok, all clear in https://github.com/jazzband/django-smart-selects/pull/323

The changes are small so no need to release. Please go ahead with GitHub Actions.

**Comment by jezdez** [comment]
> @jezdez ok, all clear in #323
> 
> The changes are small so no need to release. Please go ahead with GitHub Actions.

Great, thank you, I've merged the PR and we can work out what to do next.

**Comment by manelclos** [comment]
@jezdez ok to release?

**Pull request merged**
