### PR TITLE
fix force text enconding support for django 4

### PR DESCRIPTION
**Pull request by diego1996**

### CODE REVIEW

**Comment by manelclos** [comment]
Hi @diego1996 can you please remove the .idea files?

**Comment by diego1996** [comment]
> Hi @diego1996 can you please remove the .idea files?

Yeah, I hadn't realised.

**Comment by manelclos** [comment]
Hi @diego1996,

I had no problems when including Django 4.0 in the tests matrix, see this PR for tests results: https://github.com/jazzband/django-smart-selects/pull/322

Also, Django 4.0 is deprecating force_text, not force_str:
https://docs.djangoproject.com/en/4.0/releases/4.0/#features-removed-in-4-0

Can you please elaborate on why this PR is needed?

**Comment by luzdealba** [comment]
Thanks for this patch, @[diego1996](https://github.com/diego1996)!

This PR fixed a Django v4 deprecation issue for me; and it's also written in `try`/`except` block that keeps v3 backwards compatibility.

You should consider merging it to master.

Best.

**Comment by Blind-Watchmaker** [comment]
What is the status on this issue? I'm trying to migrate my project to Django 4.0 and `django-smart-selects` is the only package that is holding me back.
```
from django.utils.encoding import force_text
ImportError: cannot import name 'force_text' from 'django.utils.encoding' (/Users/willmusgrave/Development/bluenode/product/env/lib/python3.8/site-packages/django/utils/encoding.py)
```

**Comment by manelclos** [comment]
@diego1996 can you please fix the PR?

**Comment by manelclos** [comment]
@Blind-Watchmaker django-smart-selects 1.6.0 is out and features django 4.0 support. Please let me know if you test it. Thanks!

https://pypi.org/project/django-smart-selects/

**Comment by diego1996** [comment]
Hola chicos, perdon lo tarde, recien lo veo, que bueno que ya se halla solucionado el problema.

**Comment by diego1996** [comment]
Voy a declinar este PR

**Pull request closed without merging**
